/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A stateless strategy-test session. Tests and data are passed with each command. */
export declare class Session {
  constructor()
  /** Run a command envelope (`{"cmd":"...", ...}`) and return the response JSON. */
  command(cmdJson: string): string
  /** The crate version. */
  version(): string
}
